### ISSUE TITLE
Need some parameter adjustments

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#15]
Lack
- [ ]  xcmsSet.findPeaks.centWave mzCenterFun
- [ ]  xcmsSet.findPeaks.centWave fitgauss
- [ ]  xcmsSet.findPeaks.matchedFilter sigma
- [x]  xcmsSet.findPeaks.matchedFilter mzdiff
- [ ]  group.density minsamp
- [ ]  retcor.obiwrap distFunc
- [ ]  retcor.obiwrap plottype
- [ ]  retcor.obiwrap gapInit
- [ ]  retcor.obiwrap gapExtend
- [ ]  retcor.obiwrap response
- [ ]  retcor.obiwrap factorDiag
- [ ]  retcor.obiwrap factorGap
- [ ]  retcor.obiwrap localAlignment

Wrong
- [ ] xcmsSet.findPeaks.matchedFilter step is set at 0.01 but the default is 0.1
- [ ] group.density max is set at 5 but default is 50

Other
- [x]  xcmsSet.findPeaks.centWave integrate we have to add `1 -` or `2 -`  in the option labels

**Comment by lecorguille** [comment]
ping @mmonsoor @yguitton @jfrancoismartin 

I'm working on IPO and I do something I never did: read the doc. Or maybe, we can consider that as an update, who know (or want to know)

Indeed, because I get IPO parameters, I observe that there are many more parameters we can set in IPO are not available in the xcms* wrappers.

Although, I'm involved in the xcms wrappers development, currently, I don't know if those parameters were omitted or forgotten
Maybe there are not so usefull? But I remember that we claim the completeness of our parameters for avanced users.

So far, I have only look at xcmsSet and retcor.

So can you, expert and developpers, help me to filter this bunch of options. I can honestly propose some IPO parameters that are not in the following steps (xcmsSet, retcor)

Many thanks ❤️

**Comment by jfrancoismartin** [comment]
@lecorguille @yguitton @mmonsoor 
Hi
In my point of view, matchedFilter mzdiff must be add as It's an important parameter and wrong default value must be changed.
Other findpeaks parameters (centwave and machedfilter) could be add because of compleness but there are not in xcmsOnline parameters (even in the advanced ones). Same for obiwarp, I didn't even knew them. But if we want to be more catholic than the pope...

For IPO, as the treatment could long, may be a set of important parameters for xcmsSet and group could be proposed. for xcmsSet, ppm, min and max peakwitdh for centwave or step and FWHM for matchedfilter and mzdiff for both. For group, BW and mzwid.
What do you think about it ?

**Comment by lecorguille** [comment]
@jfrancoismartin 
Ok, in this first round, I wil just add `xcmsSet.findPeaks.matchedFilter mzdiff`. I guess that the other parameters don't target our users.

What about the **Wrong default value**
- xcmsSet.findPeaks.matchedFilter step is set at 0.01 but the default is 0.1
- group.density max is set at 5 but default is 50
Should we change them as the default one?

**Comment by lecorguille** [comment]
@yguitton @melpetera @jfrancoismartin 

I need your help about those **Wrong default value**
- xcmsSet.findPeaks.matchedFilter step is set at 0.01 but the default is 0.1
- group.density max is set at 5 but default is 50

I don't know why those values were chosen. I guess they were set during Urzsula internship or by Misharl? But maybe, one of you ask "us" to change them? Or were they set according to xcmsonline? (I try to check in xcmsonline, but I can't find anywhere the tools settings without have to select a hardware!)

Anyway, should we change them as the default one?

**Comment by melpetera** [comment]
@lecorguille When I first tested our XCMS Galaxy version 3 years ago, I noticed these differences in default values. I remember noticing it to "Roscoff staff" (that means Misharl and/or you - I can't find any corresponding email... I think I reported it during one of our visioconference) and I remember Etienne saying that he also noticed this. And I remember that at that time the reason why it was this way was already not clear (a typo? XCMSonline parameters? Previously chosen?). Anyway during my search I did not find examples of parameter set containing 0.01 and 5. 

Since the other parameters were the default ones (at least for those I managed to find what were the default values), then I assumed it was just typo, and anyway I wrote in my laboratory "best practice" not to forget to initialise these two values with real default ones (since they were the ones we used before the Galaxy version). 

I don't know if this help you or not. If it is about opinion, I would rather suggest to switch to the default ones, since this makes it easier I think for new Galaxy users wanting to compare to their previous XCMS pipeline without being some XCMS experts.

**Comment by lecorguille** [comment]
@melpetera I get this email, indeed :)
Do you know other wrong default values?

So, yes, I definitely agree to switch to the good default values.
And we will have to communicate on it in the change logs :/

**Comment by melpetera** [comment]
I did not notice other wrong default values. Appart from the parameters we usually adjusted before beginning to use the Galaxy version (which includes the step parameter), the only parameter I had to adjust to obtain exactly the same results with Galaxy is the group.density max one, and this on several test datasets having nothing to do one with the others (different matrices, ionization mode, device...). So even if there were some remaining parameters I did not checked yet, I just assumed they were set with the right default values.

**Comment by lecorguille** [comment]
Done

**Comment by jfrancoismartin** [comment]
A comment about xcmsSet.findPeaks.matchedFilter step and max
For me, matchedFilter is a method to use for low resolution mass spec so step=0.1 and max=5 are good values in this case.
If one use matchfilter for high resolution, he must use 0.01 and 50 but for me **it is not the right method**, centwave must be used...
It helps you ?

**Comment by jfrancoismartin** [comment]
For default values, in my opinion,  xcms.group bandwith should be set to 10 (instead of 30)
