### ISSUE TITLE
New updates in XCMS and CAMERA v 1.50 can affect W4M

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/xcms#34]
Just a warning some deep changes have been added into XCMS and CAMERA for XCMS >1.50, those can affect our tools

**Comment by lecorguille** [comment]
@workflow4metabolomics/ms 

According to this documentation https://bioconductor.org/packages/3.4/bioc/news/xcms/NEWS,
the main new features since the 1.46 are:

**CHANGES IN VERSION 1.49.6**
USER VISIBLE CHANGES:
+ Peak Picking function findPeaks.centWaveWithPredictedIsotopeROIs() and findPeaks.addPredictedIsotopeFeatures(),
  which allow more sensitive detection of isotope features.

**CHANGES IN VERSION 1.49.3**
USER VISIBLE CHANGES:
+ xcms uses now BiocParallel for parallel processing. All other parallel
  processing functions have been deprecated.

Do I miss something?

 - For `BiocParallel`, I don't see any real change for the tool except that we don't need to load `snow` anymore.
 - About `findPeaks.centWaveWithPredictedIsotopeROIs()` and `findPeaks.addPredictedIsotopeFeatures()`, should I implement them both as the same level as `centWave` and `matchedFilter`

**Comment by jfrancoismartin** [comment]
I didn't read yet the publication about those changes. May be we could wait a litle bit and check before the modification of extraction. no?

**Comment by yguitton** [comment]
all this is managed by the new xcms3.0 w4M tool made by @lecorguille
