### ISSUE TITLE
add unzip to the requirements of xcms.xcmsSet 

### ISSUE THREAD

**Issue by bernt-matthias** [workflow4metabolomics/xcms#75]
Since unzip might not be available on a cluster environment (as in our case on CentOS) it should be in the requirements. 

With zip file import the tool failed with a cryptic error:

```
find: `NA': No such file or directory
find: `/gpfs1/data/galaxy_server/galaxy/jobs_dir/006/6477/working/NA': No such file or directory
Warning message:
running command 'find $PWD/NA -not -name '\.*' -not -path '*conda-env*' -type f -name "*"' had status 1 
Error in xcmsSet(NA_character_, nSlaves = 1, method = "matchedFilter",  : 
  No NetCDF/mzXML/mzData/mzML files were found.
Calls: do.call -> do.call -> xcmsSet
Execution halted
```

The file list returned by unzip seems to be empty and therefore the root directory is undetermined. Checking for this might also be a good idea. 

@lecorguille maybe you can include this in your efforts while you are working on the merger anyway

**Comment by lecorguille** [comment]
I though that if it runs on Travis, it should run everywhere.
Anyway, I added unzip in the requirements https://github.com/workflow4metabolomics/xcms/pull/84/commits/13a13c43c3637cc9ee9b22d55f76f7fdcbbc0528 in the future xcms3 wrappers.
I didn't test so much because I can't deinstall unzip on my mac.
Let me know
