### ISSUE TITLE
New Chromatogram objects

### ISSUE THREAD

**Issue by jotsetung** [workflow4metabolomics/xcms#83]
Hi, tremendous work you're doing! Awesome!

Just wanted to point you to the new `Chromatogram`/`Chromatograms` class in `MSnbase`. It is now very easy to extract ion chromatograms (or base peak or TIC). If you have an `OnDiskMSnExp` or `MSnExp` you can simply use the `chromatogram` method. This returns a `Chromatograms` object which is simply a `matrix` like object containing `Chromatogram`s. Rows can be different slices (m/z, rt ranges) of the MS data, columns are for the individual samples/files.

The `chromatogram` method has also parameters `mz` and `rt` that allow to restrict to a certain m/z-rt slice of the MS data. The `aggregationFun` allows to define how signals for the same rt are handled - for a TIC you would use `aggregationFun = "sum"`, for a BPC `aggregationFun = "max"`.

You can then use the `plot` method to plot the chromatographic data.

Have also a look at `?MSnbase::chromatogram` and `?xcms::chromatogram`. For `XCMSnExp` objects there is an additional parameter `adjustedRtime` that allows to specify whether the raw or adjusted retention time should be reported.

**Comment by lecorguille** [comment]
After the parameters, it was my next move to provide almost the same visualisations we did but with the new features based on MSnBase: TIC, BPC and EIC.

In parallel, with @RomainDallet, we are also working on some [Galaxy Interactive Environments (GIE)](https://docs.galaxyproject.org/en/master/admin/interactive_environments.html) to provide interactive visualisation to explore data and spectra: zoom, drag and drop, selection, labels, hide some track...
They will be based on Shiny application nested in some Docker image (GIE have to run in Docker Container).
Unfortunately, we have to deal also with the raw data since I choose the `OnDiskMSnExp` object. So, we have to get/download the raw (using the Galaxy API) inside the container next to the RData. A lot of fun 😄 

I will keep this thread open as an exchange place between you and @RomainDallet, if it is ok for you.

**Comment by lecorguille** [comment]
- [x] [plotChromPeakDensity](https://github.com/workflow4metabolomics/xcms/pull/85/commits/80390261e35b38ef4893b495b4813ab1c22c0ea1)
