### ISSUE TITLE
Error with files with comma in name 

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/xcms#93]
from sneumann

A new strange file name issue

The issue seems to be something about quoting
when using files that contain a comma, see also the below
error message

"cannot symlink
'/work/proj....715/dataset_715962.dat' to
'ftp://ftp.e....MTBLS2/MSpos-Ex1-Col0-48h-Ag-3_1-A'
reason 'No such file or directory'"

where the source filename is truncated MSpos-Ex1-Col0-48h-Ag-3_1-A
after the comma where it should've been
MSpos-Ex1-Col0-48h-Ag-1_1-A,1_01_9818.mzData

**Comment by sneumann** [comment]
... and the reason seems to be in 
https://github.com/workflow4metabolomics/xcms/blob/73791d74546087b2a872d9279df960f5bc207298/tools/scripts/lib.r#L497
which has a `singlefile_galaxyPaths = unlist(strsplit(singlefile_galaxyPaths,","))`
It would be great to have an example how `singlefile_galaxyPaths` looks like.
My guess would be that it would be that this expects: 
```
> unlist(strsplit(singlefile_galaxyPaths<-"file1.mzML,file2.mzML", ","))
[1] "file1.mzML" "file2.mzML"
```
which gets into trouble in case of:
```
> unlist(strsplit(singlefile_galaxyPaths<-"file1-A,1-4711.mzML,file2-A,2-4712.mzML", ","))
[1] "file1-A"     "1-4711.mzML" "file2-A"     "2-4712.mzML"
```
A suggestion would be to send the `singlefile_galaxyPaths` around as parsed (and hence quoted) 
R expressions which can be transported as a single string:
```
> singlefile_galaxyPaths <- c("file1-A,1-4711.mzML","file2-A,2-4712.mzML")
> deparse(singlefile_galaxyPaths)
[1] "c(\"file1-A,1-4711.mzML\", \"file2-A,2-4712.mzML\")"
```
then it is possible to parse and evaluate/execute the above expression:
```
> eval(parse(text=deparse(singlefile_galaxyPaths)))
[1] "file1-A,1-4711.mzML" 
[2] "file2-A,2-4712.mzML"
```
Yours, Steffen

**Comment by lecorguille** [comment]
Hi @sneumann,
Sorry for that, I'm aware of this bug, it had been reported in this issue: https://github.com/workflow4metabolomics/xcms/issues/68
I fixed it in the new version of the wrappers for xcms 3.0.

I hope to release it soon. But there are still some issues with the connexion between xcms 3.0 and camera: https://github.com/workflow4metabolomics/camera/pull/38
I'm back from holiday and fresh 👍
